repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.103.0
  hooks:
    - id: terraform_fmt
      args:
        - --hook-config=--no-wsl
    - id: terraform_docs
      args:
        - --hook-config=--no-wsl
    - id: terraform_tflint
      args:
        - --hook-config=--no-wsl
        - --args=--config=.tflint.hcl
    - id: terraform_checkov
      args:
        - --hook-config=--recursive
        - --hook-config=--no-wsl
        - --args=--config-file .checkov.yaml

- repo: https://github.com/bridgecrewio/checkov.git
  rev: 3.2.490
  hooks:
    - id: checkov
      args: [--config-file, .checkov.yaml]