global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ecs-tasks'
    ec2_sd_configs:
      - region: ${aws_region}
        port: 9090
    relabel_configs:
      - source_labels: [__meta_ec2_tag_ECS_Task]
        regex: (.+)
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance

  - job_name: 'node-exporter'
    ec2_sd_configs:
      - region: ${aws_region}
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_NodeExporter]
        regex: true
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance

  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
